
POST http://localhost:5132/pizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "isGlutenFree": false
}

###

PUT http://localhost:5132/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

GET http://localhost:5132/pizza/3
Accept: application/json

###
DELETE http://localhost:5132/pizza/3

###
GET http://localhost:5132/pizza/
Accept: application/json